ingress:
  host: localhost
  
replicaCount: 1

image:
  tag: "latest"
  repository: "example_public_api"
  
resources:
  limits:
    cpu: 0.5
    memory: 1Gi
  requests:
    cpu: 0.05
    memory: 100Mi

deploy:
  elastic:
    apm:
      server: "http://192.168.34.111:8200"
      agent:
        volumes: "/host_mnt/c/work/meta/services/src/Helpers/ElasticApmAgent"
  http:
    path: "/"
    port: "5101"

settings:
  database:
    connection:
      example: "Host=host.docker.internal;Port=5432;Database=meta-example;Username=meta;Password=meta;Include Error Detail=True"
      
  locations:
    api:
      baseUrl: "http://host.docker.internal:5101"
  
  features:
    authorization:
      keycloak:
        authority:  "http://vlg.unrealenginecgi:8090/realms/meta"
        client:
          id: "signaling"
    logging:
      serilog:
        minimumLevel: "Debug"
    elastic:
      nodes: "http://host.docker.internal:9200"
      
  rabbitMq:
    client:
      hosts: "host.docker.internal,host.docker.internal"
      userName: "guest"
      password: "guest"
      virtualHost: "Meta"
      port: "5672"
        
  clients:
    weatherForecast:
      api:
        baseUrl: "http://host.docker.internal:5102"