@Meta.Private.Hosts.Api_HostAddress = http://localhost:5100

DELETE {{Meta.Private.Hosts.Api_HostAddress}}/forecast/weather/03-14-2024
Accept: application/json
Authorizationheader: TrustedNetwork Service

###
