---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  labels:
    app/name: {{ $.Chart.Name }}-http
    app/instance: {{ $.Release.Name }}-http
  name: "{{ $.Release.Name }}-http"
spec:
  rules:
    - host: {{ $.Values.ingress.host }}
      http:
        paths:
          - path: {{ $.Values.deploy.http1.path }}
            pathType: Prefix
            backend:
              service:
                name: "{{ $.Release.Name }}-http"
                port:
                  number: {{ $.Values.deploy.http1.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  labels:
    app/name: {{ $.Chart.Name }}
    app/instance: {{ $.Release.Name }}
  name: {{ $.Release.Name }}
spec:
  rules:
    - host: {{ $.Values.ingress.host }}
      http:
        paths:
          - path: {{ $.Values.deploy.http2.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  number: {{ $.Values.deploy.http2.port }}
