---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-http"
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.deploy.http1.port }}
      targetPort: {{ .Values.deploy.http1.port }}
      name: http
  selector:
    app: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.deploy.http2.port }}
      targetPort: {{ .Values.deploy.http2.port }}
      protocol: TCP
      name: grpc
  selector:
    app: {{ .Release.Name }}