apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-consumer
  template:
    metadata:
      labels:
        app: example-consumer
    spec:
      containers:
        - name: example-consumer
          image: example_consumer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: "DOTNET_ENVIRONMENT"
              value: "Docker"
            - name: "ELASTIC_APM_SERVICE_NAME"
              value: example-consumer
            - name: "DOTNET_STARTUP_HOOKS"
              value: "/app/ElasticApmAgent/ElasticApmAgentStartupHook.dll"
            - name: "ELASTIC_APM_SERVER_URL"
              value: "http://192.168.34.111:8200"
          volumeMounts:
          - name: elastic-apm-agent-hook
            mountPath: /app/ElasticApmAgent
            readOnly: true
      volumes:
        - name: elastic-apm-agent-hook
          hostPath:
            path: "/host_mnt/c/work/meta/services/src/Helpers/ElasticApmAgent"
            type: Directory